Match zMusicUnpause
bfbbdecomp/bfbb pull request #391
Opened 2024-10-11 18:23 UTC by escape209

Thanks @tgsm
Also remove outdated comment and match getCurrLevelMusicEnum linkage
Tried to find more stuff to put in here but it's a tough file 💀

2024-10-11 18:57 UTC, SquareMan requested changes

2024-10-11 18:57 UTC, SquareMan commented on src/SB/Game/zMusic.h
> +static S32 getCurrLevelMusicEnum();
This function declaration should be removed from the header since other cpp files won't be able to call this function

2024-10-11 18:57 UTC, SquareMan commented on src/SB/Game/zMusic.cpp
>  S32 getCurrLevelMusicEnum()
Looks like this should be static since you changed the prototype?

2024-10-12 07:33 UTC, escape209 commented
Integrated both of the changes

2024-10-12 17:57 UTC, merged