Some work on decomping NPCs
bfbbdecomp/bfbb pull request #66
Opened 2020-12-25 20:49 UTC by earthcrafterman

Moved UVAModelInfo to NPCTypes
Decomped UVAModelInfo::Hemorrage
Decomped PlayTheFiddle, RobotShutdown, ScenePrepare, SceneFinish, SceneReset, ScenePostInit, Timestep, DestroyRobot, and NPCRobot, ColChkFlags, ColPenFlags, PhysicsFlags, and Process in NPCTypeRobot
Setup some of NPCCommon's vTable
Decomped Startup and Shutdown in zNPCTypes' Startup and Shutdown Functions
Decomped zNPCTiki Startup and Shutdown

2020-12-25 23:57 UTC, mattbruv requested changes
To start, `make` doesn't work for me, it errors:

```
### mwcceppc.exe Compiler:
#    File: src\Game\zNPCTypes.cpp
# -------------------------------
#       5: #include <zNPCTypeCommon.h>
#   Error:                           ^
#   the file 'zNPCTypeCommon.h' cannot be opened
### mwcceppc.exe Compiler:
#       6: #include <zNPCTypeRobot.h>
#   Error:                          ^
#   the file 'zNPCTypeRobot.h' cannot be opened
### mwcceppc.exe Compiler:
#       7: #include <zNPCTypeTiki.h>
#   Error:                         ^
#   the file 'zNPCTypeTiki.h' cannot be opened
### mwcceppc.exe Compiler:
#       8: #include <zNPCTypeDuplotron.h>
#   Error:                              ^
#   the file 'zNPCTypeDuplotron.h' cannot be opened
### mwcceppc.exe Compiler:
#       9: #include <zNPCTypeVillager.h>
#   Error:                             ^
#   the file 'zNPCTypeVillager.h' cannot be opened
### mwcceppc.exe Compiler:
#      10: #include <zNPCTypeAmbient.h>
#   Error:                            ^
#   the file 'zNPCTypeAmbient.h' cannot be opened
### mwcceppc.exe Compiler:
#      11: #include <zNPCTypeSubBoss.h>
#   Error:                            ^
### mwcceppc.exe Compiler:
#      12: #include <zNPCTypeBoss.h>
#   Error:                         ^
#   the file 'zNPCTypeBoss.h' cannot be opened
### mwcceppc.exe Compiler:
#      13: #include <zNPCTypeTest.h>
#   Error:                         ^
#   the file 'zNPCTypeTest.h' cannot be opened
```

How you include files seems to be wrong

Also, you need to run clang-format, because my script detected it needs to be run on these files:

```
        modified:   src/Game/zNPCGlyph.h
        modified:   src/Game/zNPCHazard.h
        modified:   src/Game/zNPCTypeRobot.cpp
        modified:   src/Game/zNPCTypeRobot.h
        modified:   src/Game/zNPCTypeTiki.cpp
        modified:   src/Game/zNPCTypes.h
```

2020-12-26 00:28 UTC, stravant commented
> bool zNPCTiki::IsHealthy()

This function is already a match as a bool, and becomes non-matching if changed to an int32 as the return type, so zNPCCommon must actually have `virtual bool IsHealthy();` for things to work, not `virtual int32 IsHealthy();`. Given that the other "is" functions in there are probably bools too.

2020-12-26 00:36 UTC, stravant commented
Also, for the other errors, the problem is that you need to use quoted includes in `zNPCTypes.cpp`, not angle bracket ones. Angle bracket includes only work for "system headers" (from the `-I` option on the compiler), not relative paths to other files in the directory.

2020-12-26 13:33 UTC, mattbruv commented on src/Game/zNPCTypeCommon.h
> +	virtual void RenderExtra();
`src/Game/zNPCTypeCommon.h` isn't formatted properly

2020-12-26 20:11 UTC, mattbruv approved these changes
Good work

2020-12-26 20:11 UTC, merged